/*
 * Skynet API
 *
 * This is the skynet infrastructure api
 *
 * The version of the OpenAPI document: 0.1
 * Contact: contact@guillaume-etheve.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Broadcast {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<String>,
    #[serde(rename = "server_kind", skip_serializing_if = "Option::is_none")]
    pub server_kind: Option<String>,
}

impl Broadcast {
    pub fn new(message: String) -> Broadcast {
        Broadcast {
            message,
            permission: None,
            server_kind: None,
        }
    }
}


