/*
 * Skynet API
 *
 * This is the skynet infrastructure api
 *
 * The version of the OpenAPI document: 0.1
 * Contact: contact@guillaume-etheve.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Leaderboard {
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "leaderboard")]
    pub leaderboard: Vec<String>,
}

impl Leaderboard {
    pub fn new(label: String, leaderboard: Vec<String>) -> Leaderboard {
        Leaderboard {
            label,
            leaderboard,
        }
    }
}


