/*
 * Skynet API
 *
 * This is the skynet infrastructure api
 *
 * The version of the OpenAPI document: 0.1
 * Contact: contact@guillaume-etheve.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PingInfo {
    #[serde(rename = "online")]
    pub online: i32,
    #[serde(rename = "slots")]
    pub slots: i32,
    #[serde(rename = "motd")]
    pub motd: String,
}

impl PingInfo {
    pub fn new(online: i32, slots: i32, motd: String) -> PingInfo {
        PingInfo {
            online,
            slots,
            motd,
        }
    }
}


