/*
 * Skynet API
 *
 * This is the skynet infrastructure api
 *
 * The version of the OpenAPI document: 0.1
 * Contact: contact@guillaume-etheve.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlayerMove {
    #[serde(rename = "server", skip_serializing_if = "Option::is_none")]
    pub server: Option<String>,
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "admin_move", skip_serializing_if = "Option::is_none")]
    pub admin_move: Option<bool>,
}

impl PlayerMove {
    pub fn new() -> PlayerMove {
        PlayerMove {
            server: None,
            kind: None,
            admin_move: None,
        }
    }
}


