/*
 * Skynet API
 *
 * This is the skynet infrastructure api
 *
 * The version of the OpenAPI document: 0.1
 * Contact: contact@guillaume-etheve.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProxyPreLoginResponse {
    #[serde(rename = "result")]
    pub result: Result,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<Vec<crate::models::MessageComponent>>,
}

impl ProxyPreLoginResponse {
    pub fn new(result: Result) -> ProxyPreLoginResponse {
        ProxyPreLoginResponse {
            result,
            message: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "Allowed")]
    Allowed,
    #[serde(rename = "Denied")]
    Denied,
}

impl Default for Result {
    fn default() -> Result {
        Self::Allowed
    }
}

