/*
 * Skynet API
 *
 * This is the skynet infrastructure api
 *
 * The version of the OpenAPI document: 0.1
 * Contact: contact@guillaume-etheve.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProxyLoginRequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "ip")]
    pub ip: String,
    #[serde(rename = "proxy")]
    pub proxy: String,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<String>,
}

impl ProxyLoginRequest {
    pub fn new(username: String, ip: String, proxy: String, version: String) -> ProxyLoginRequest {
        ProxyLoginRequest {
            username,
            ip,
            proxy,
            version,
            locale: None,
        }
    }
}


