/*
 * Skynet API
 *
 * This is the skynet infrastructure api
 *
 * The version of the OpenAPI document: 0.1
 * Contact: contact@guillaume-etheve.fr
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServerLoginPlayerInfo {
    #[serde(rename = "session")]
    pub session: String,
    #[serde(rename = "proxy", skip_serializing_if = "Option::is_none")]
    pub proxy: Option<String>,
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "suffix", skip_serializing_if = "Option::is_none")]
    pub suffix: Option<String>,
    #[serde(rename = "locale")]
    pub locale: String,
    #[serde(rename = "permissions")]
    pub permissions: Vec<String>,
    #[serde(rename = "power")]
    pub power: i32,
    #[serde(rename = "currency")]
    pub currency: i32,
    #[serde(rename = "premium_currency", skip_serializing_if = "Option::is_none")]
    pub premium_currency: Option<i32>,
    #[serde(rename = "blocked")]
    pub blocked: Vec<String>,
    #[serde(rename = "inventory")]
    pub inventory: ::std::collections::HashMap<String, i32>,
    #[serde(rename = "properties")]
    pub properties: ::std::collections::HashMap<String, String>,
    #[serde(rename = "discord_id", skip_serializing_if = "Option::is_none")]
    pub discord_id: Option<String>,
    #[serde(rename = "mute", skip_serializing_if = "Option::is_none")]
    pub mute: Option<Box<crate::models::Mute>>,
}

impl ServerLoginPlayerInfo {
    pub fn new(session: String, locale: String, permissions: Vec<String>, power: i32, currency: i32, blocked: Vec<String>, inventory: ::std::collections::HashMap<String, i32>, properties: ::std::collections::HashMap<String, String>) -> ServerLoginPlayerInfo {
        ServerLoginPlayerInfo {
            session,
            proxy: None,
            prefix: None,
            suffix: None,
            locale,
            permissions,
            power,
            currency,
            premium_currency: None,
            blocked,
            inventory,
            properties,
            discord_id: None,
            mute: None,
        }
    }
}


